---
- stat: path='/opt/activator-dist-{{ lightbend_activator_version }}'
  register: activatordir
  
- name: Download Typesafe Activator
  when: activatordir.stat.exists == false
  get_url: url={{ lightbend_activator_url }} dest="/tmp/{{ lightbend_activator_archive }}"

- name: Unzip Typesafe Activator
  when: activatordir.stat.exists == false
  unarchive: copy=no src='/tmp/{{ lightbend_activator_archive }}' dest=/opt

- name: make executable
  file: >-
    path='/opt/activator-dist-{{lightbend_activator_version}}/bin/activator'
    mode=0755
  
- name: Link Typesafe Activator
  file: src='/opt/activator-dist-{{ lightbend_activator_version }}' dest=/opt/activator state=link

- name: include activator in the PATH
  copy: >-
    src=etc/profile.d/activator.sh
    dest=/etc/profile.d/activator.sh
    mode=0644
    owner=root
    group=root
