---
- name: download...
  become: yes
  become_user: root
  get_url:
    url: '{{lightbend_activator_url}}'
    dest: /tmp/{{lightbend_activator_zip}}

- name: unzip...
  become: yes
  become_user: root
  unarchive:
    copy: no
    src: /tmp/{{lightbend_activator_archive}}
    dest: '{{lightbend_activator_install_parent_dir}}'
    creates: '{{lightbend_activator_install_dir}}'

- name: make executable...
  become: yes
  become_user: root
  file:
    path: '{{lightbend_activator_install_dir}}/bin/activator'
    mode: 0755
  
- name: link...
  become: yes
  become_user: root
  file:
    src: '{{lightbend_activator_install_dir}}'
    dest: '{{lightbend_activator_install_parent_dir}}/activator'
    state: link

- name: include activator in the PATH
  become: yes
  become_user: root
  with_items:
    - f: activator.sh
      d: /etc/profile.d
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: 0644
